export const fms = [
  "Procurement Services and Travel Agents",
  "Recruitment",
  "Financial Brokerage",
  "Real Estate Brokerage and Support Services",
  "Diversified Services",
  "Supervisors",
  "Management, Administration, and Consulting",
  "Agricultural Regulation",
  "Goverment, Law, and Regulation",
  "Transportation Regulation",
  "Healthcare",
  "Veterinary Services",
  "Customer Service",
  "Software Development",
  "Media Editors",
  "Real Estate Maintenance",
  "Home Good and Appliance Repair",
  "Repair and Maintenance",
  "Medical Equipment Technicians",
  "Waste Management",
  "Electrical and Mechanical Repair and Maintenance",
  "Vehicle Repair and Maintenance",
  "Industrial Repair and Maintenance",
  "Apparel Cleaning and Maintenance",
  "Personal Care",
  "Animal Management",
  "Appliance and Electronics Rental",
  "Office Supply Rental",
  "Diversified Rentals",
  "Home Health Equipment Rental",
  "Industrial Equipment Rental",
  "Libraries and Archives",
  "Information Management",
  "Protective Service Workers",
  "Agricultural Inventory",
  "Inventory",
  "Human Resources",
  "Labor Contractors",
  "Media Distribution",
  "Patent Licensing",
  "Software Platforms",
  "Internet Publishing",
  "Mail Centers",
  "Mining and Logging and Agricultural Real Estate Operators",
  "Real Estate Lessors",
  "Transportation and Shipping Real Estate Operators",
  "Hotels",
  "Residential Healthcare Facilities",
  "Conservation",
  "Recreational and Event Space Operation",
  "Electronics and Appliance Rental",
  "Office and Commercial Rentals",
  "Office and Commercial Goods Rental",
  "Laundry and Clothing Rental",
  "Recreational Goods Rental",
  "Vehicle Rental and Operation",
  "Caretaking",
  "Dental Assistants",
  "Legal Clerks and Secretaries",
  "General Secretaries and Administrative",
  "Inspectors and Screeners",
  "Public Order and Safety",
  "Information Security",
  "Home Security Monitoring",
  "Food Delivery and Storage",
  "Apparel Storage",
  "Vehicle Storage",
  "Correctional Institutions",
  "Food and Beverage Production",
  "Agriculture",
  "Food Preparation and Service",
  "Pharmaceutical Manufacturing",
  "Animal Breeding",
  "Diversified Manufacturing and Packaging",
  "Energy Production",
  "Art and Media Production",
  "Financial Services",
  "News Production",
  "Documentation, Recording, and Printing",
  "Construction",
  "Home Goods, Furniture, and Appliance Manufacturing",
  "Office and Commercial Goods Manufacturing",
  "Medical Equipment Manufacturing",
  "Materials Manufacturing and Mining",
  "Animal Production",
  "Real Estate Component Manufacturing",
  "Textile Manufacturing",
  "Electronic and Electrical Component Manufacturing",
  "Paper, Packaging, and Film Manufacturing",
  "Mechanical Component Manufacturing",
  "Industrial Equipment Components Manufacturing",
  "Vehicle Component Manufacturing",
  "Industrial Equipment Manufacturing",
  "Weapon Manufacturing",
  "Electronics Manufacturing",
  "Apparel and Jewelry Production",
  "Recreational Goods Manufacturing",
  "Shipping Equipment Manufacturing",
  "Advocacy, Counseling, Religous Organizations, and Social Services",
  "International Affairs",
  "Urban, Regional, and Environmental Planning",
  "Pharmaceutical Retail",
  "Agents",
  "Energy and Utility Distribution",
  "News and Media Retail",
  "Retail, Wholesale, and Distribution",
  "Advertising",
  "Order Verification",
  "Title Examiners",
  "Food and Beverage Distribution",
  "Agricultural Product Sales",
  "Produce Sales",
  "Bars and Restaurants",
  "Grocery Stores",
  "Diversified Sales",
  "Real Estate Brokerage",
  "Mobile Home Dealers",
  "Market Research",
  "Food and Animal Science",
  "Biotech Research",
  "Energy Sciences",
  "Consumer Media Creation",
  "Computer and Information Science",
  "Graphic Design",
  "Drafting and Design",
  "Architecture and Interior Design",
  "Network Architecture",
  "Fashion Design",
  "Training and Education",
  "Animal Training",
  "Engineering",
  "Research",
  "Passenger Transportation",
  "Shipping and Warehousing",
  "Energy Transportation and Transmission",
  "Telecoms, Communications, and Mail Service",
  "Moving and Delivery",
  "Materials Moving",
  "Logistics",
  "Live Entertainment",
  "Investment Servicds and Financial Advisory",
  "Casinos and Gambling",
  "Insurance",
  "Banking and Loans",
  "Grants and Public Program Administration",
];

export const counties = [
  "Calhoun County, AL",
  "Mohave County, AZ",
  "Orange County, CA",
  "El Paso County, CO",
  "Summit County, CO",
  "Brevard County, FL",
  "Jackson County, FL",
  "Chatham County, GA",
  "Polk County, IA",
  "St. Clair County, IL",
  "Jefferson County, KY",
  "Garrett County, MD",
  "Eaton County, MI",
  "Hennepin County, MN",
  "Buncombe County, NC",
  "Seneca County. NY",
  "Suffolk County, NY",
  "Knox County, OH",
  "Juniata County, PA",
  "Parker County, TX",
  "Dickson County, TN",
  "Gloucester County, VA",
  "White County, AK",
  "New Haven County, CT",
  "Sussex County, DE",
  "Clearwater County, ID",
  "DeKalb County, IN",
  "East Baton Rouge Parish, LA",
  "Oxford County, MA",
  "Clarke County, MS",
  "Dallas County, MO",
  "Garfield County, MT",
];
